version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: spotify
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
